rules:
  - id: third-party-action-not-pinned-to-commit-sha
    pattern-either:
      - pattern: uses: $ACTION@$REF
        metavariable-regex:
          $ACTION: ^(?!.*?/\.)(?!actions/).*?/.*?$
          $REF: ^(v?\d+(\.\d+){0,2}|[^@]+)$
      - pattern: uses: $ACTION
        metavariable-regex:
          $ACTION: ^(?!.*?/\.)(?!actions/).*?/.*?$
    message: >
      Third-party GitHub Action is not pinned to a specific commit SHA.
      This can be a security risk as the action may be modified unexpectedly.
      Consider using a full length commit SHA instead of a tag or branch name.
    severity: WARNING
    languages: [yaml]
    paths:
      include:
        - '**/workflows/*.yml'
        - '**/workflows/*.yaml'
    metadata:
      category: security
      technology:
        - github-actions
      references:
        - https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

  - id: insecure-file-permissions
    pattern: os.chmod(..., $PERMS)
    message: >
      Detected a call to os.chmod() with potentially insecure permissions.
      Ensure that file permissions are set correctly to prevent unauthorized access.
    severity: WARNING
    languages: [python]
    metadata:
      category: security
      technology:
        - python
      references:
        - https://docs.python.org/3/library/os.html#os.chmod
        - https://owasp.org/www-community/vulnerabilities/Insecure_Temporary_File
    fix-regex:
      regex: os\.chmod\((.*?),\s*(.*?)\)
      replacement: os.chmod($1, 0o600) 

