name: "\U0001F41E Bug report"
description: Report a bug on Gradio
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before you get started, please search to see if an issue already exists for the bug you encountered.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Please provide a concise description of what the bug is, in clear English.
      placeholder: Bug description
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the issue you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a minimal example, with code, that can be run to reproduce the issue. Do NOT provide screenshots of code, or link to external repos or applications.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: "If relevant, please include screenshot(s) of your Gradio app so that we can understand what the issue is."
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Please include the full stacktrace of the errors you get from Python or Javascript. If you are running in a colab notebooks, you can get the logs with by setting `debug=True`, i.e: `gradio.Interface.launch(debug=True)`"
      render: shell
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please ensure you are running a recent version of Gradio. You can get the Gradio version with `gradio.__version__`
      render: shell
      placeholder: 1. Gradio version 2. Operating system 3. (If relevant), the browser
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please ensure that you have filled all of the sections above. Incomplete issues will be closed.
