version: "3.7"
services:
  homepage:
    environment:
          - AUTH_TOKEN=${AUTH_TOKEN}
    build:
      context: ../
      args: 
        AUTH_TOKEN: ${AUTH_TOKEN}
      dockerfile: ./website/homepage/Dockerfile
    container_name: homepage
    ports:
      - "8080:80"