name: Benchmark Queue Performance

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  benchmark-queue:
    name: Benchmark Queue  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Run benchmarking script
        run: |
          python scripts/benchmark_queue.py data-this-pr.json
      - name: Get PR Number
        run: |
          python -c "import os;print(os.environ['GITHUB_REF'].split('/')[2])" > pr_number.txt
          echo "PR_NUMBER=$(cat pr_number.txt)" >> $GITHUB_ENV
      - name: Upload PR Number
        run: |
          python -c "import json; json.dump({'pr_number': ${{ env.PR_NUMBER }}},  open('metadata.json', 'w'))"
      - name: Checkout Main Branch
        if: github.ref != 'refs/heads/main'
        run: |
          git checkout main
      - name: Re-Run benchmarking script
        run: |
          python scripts/benchmark_queue.py data-main.json
      - name: Upload data and metadata
        uses: actions/upload-artifact@v3
        with:
          name: data
          path: data-this-pr.json          
          path: data-main.json          
          path: metadata.json