name: Check CHANGELOG Updated

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  check-changelog-updated:
    name: Check CHANGELOG Updated
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: ${{ !contains( github.event.pull_request.labels.*.name, 'no-changelog-update') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Release notes added
        run: |
          cat website/CHANGELOG.md | grep ":pr:\`${{ github.event.number }}\`"