name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Generate theme.css
        run: python ./scripts/generate_theme.py
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pmpm
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}