on:
  workflow_run:
    workflows: [gradio-ui]
    types: [completed]

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Generate theme.css
        run: python scripts/generate_theme.py
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}