name: Comment on pull request without race conditions

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string
      message:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: "previews"
      token:
        required: true
        type: string

concurrency:
  group: ${{ github.event.inputs.pr_number }}

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: echo token = ${{ inputs.token }}
      - run: echo pr_number = ${{ inputs.pr_number }}
      - run: echo message = ${{ inputs.message }}
      # - uses: "gradio-app/github/actions/comment_pr@main"
      #   with:
      #     github_token: ${{ inputs.token }}
      #     pr_number: ${{ inputs.pr_number }}
      #     message: ${{ inputs.message }}
      #     tag: ${{ inputs.tag }}
