name: 'Deploy to Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'gradio-app/gradio' && !contains(github.event.push.labels.*.name, 'no-visual-update') }}
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: install dependencies
        uses: "./.github/actions/install-all-deps"
        with:
          always-install-pnpm: true
          skip_build: 'true'
      - name: generate theme.css
        run: | 
          . venv/bin/activate
          python scripts/generate_theme.py --outfile js/storybook/theme.css
      - name: build storybook
        run: pnpm build-storybook --quiet
      - name: publish to chromatic
        id: publish-chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - name: post deployment link to PR
        if: steps.PR.outputs.pr_found == 'true' 
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Chromatic build result: ${{ steps.publish-chromatic.code }}
            ${{ steps.publish-chromatic.changeCount }} visual changes were found in this build.
            There are ${{ steps.publish-chromatic.errorCount }} failed tests to review. 
            * [Storybook Preview](${{ steps.publish-chromatic.outputs.storybookUrl }})
            * [Build Review](${{ steps.publish-chromatic.outputs.buildUrl }})
          GITHUB_TOKEN: ${{ secrets.COMMENT_TOKEN }}
          comment_tag: chromatic-build
          pr_number: ${{ steps.PR.outputs.number }}
