on:
  workflow_call:

jobs:
  install-deps:
    name: Install python and js deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: |
            client/python/requirements.txt
            requirements.txt
            test/requirements.txt
      - name: Create env
        run: |
          python -m pip install --upgrade virtualenv
          python -m virtualenv venv
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            venv/*
          key: gradio-lib-ubuntu-latest-pip-${{ hashFiles('client/python/requirements.txt') }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('test/requirements.txt') }}
      - name: Install Gradio (Linux)
        if: runner.os == 'Linux'
        run: |
          . venv/bin/activate
          python -m pip install .
      - name: Install Test Dependencies (Linux)
        if: steps.cache.outputs.cache-hit != 'true' && runner.os == 'Linux'
        run: |
          . venv/bin/activate
          python -m pip install -e . -r test/requirements.txt
      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
      - name: install-frontend
        uses: "gradio-app/gradio/.github/workflows/install-frontend.yml"
