name: Check for large files

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
    - name: Check for large files
      uses: actionsdesk/lfs-warning@v3.2
      with:
        filesizelimit: 5MB

