name: Check for large files

on:
  pull_request:

jobs:
  check-files:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}    
      - name: Check for large files
        uses: actionsdesk/lfs-warning@v3.2
        with:
          filesizelimit: 5MB

