rules:
  - id: detect-os-system-calls
    pattern: os.system(...)
    message: "Unsafe use of os.system(). Consider using subprocess.run() instead."
    languages: [python]
    severity: WARNING

  - id: detect-sql-injection
    pattern: 'execute("SELECT * FROM " + $TABLE)'
    message: "Potential SQL injection detected. Use parameterized queries."
    languages: [python]
    severity: ERROR

  - id: detect-eval-usage
    pattern: eval(...)
    message: "Use of eval() detected. This can be dangerous if used with untrusted input."
    languages: [python]
    severity: ERROR
