name: trigger
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
    branches:
      - main
  issue_comment:
    types: [edited]

jobs:
  checks:
    permissions: write-all
    name: static checks
    runs-on: ubuntu-22.04
    if: github.event.sender.login != 'gradio-pr-bot'
    steps:
      - run: echo "Requesting checks"
