name: gradio-ui

on:
  push:
    branches:
      - "main"
    paths:
      - "ui/**"
  pull_request:
    paths:
      - "ui/**"

# defaults:
#   run:
#     working-directory: ui

env:
  CI: true
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"

concurrency:
  group: deploy-${{ github.ref }}-${{ github.event_name == 'push' || github.event.inputs.fire != null }}
  cancel-in-progress: true

jobs:
  static-check:
    name: static checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: install dependencies
        run: pnpm i --frozen-lockfile
      - name: formatting check
        run: pnpm format:check
      - name: typecheck
        run: pnpm ts:check
        continue-on-error: true
      - name: unit tests
        run: pnpm test:run
      - name: build
        run: pnpm build
  functional-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Cache browsers
        id: browser_cache
        uses: actions/cache@main
        with:
          path: "~/.cache/ms-playwright"
          key: chromium-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: pnpm install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: ${{ steps.browser_cache.outputs.cache-hit == 'true' }}
      - run: pnpm build
      - run: pnpm test:browser:full
      - name: Upload failed tests screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          retention-days: 3
          name: test-failure-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.node-version }}
          path: test-results.tar.gz
