name: "update-checks"

on:
  workflow_run:
    workflows: ["python", "js", "functional"]
    types:
      - completed

concurrency:
  group: "${{ github.event.workflow_run.head_repository.full_name }}-${{ github.event.workflow_run.head_branch }}-${{ github.workflow_ref }}"
  cancel-in-progress: true

jobs:
  changes:
    name: "changes"
    runs-on: ubuntu-latest
    permissions:
      actions: read
    outputs:
      should_run: ${{ steps.json.outputs.should_run }}
      sha: ${{ steps.json.outputs.sha }}
      pr_number: ${{ steps.json.outputs.pr_number }}
      source_branch: ${{ steps.json.outputs.source_branch }}
      source_repo: ${{ steps.json.outputs.source_repo }}
      labels: ${{ steps.json.outputs.labels }}
      run_id: ${{ steps.json.outputs.run_id }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: changes
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - uses: gradio-app/github/actions/json-to-output@main
        id: json
        with:
          path: output.json
  update-status:
    environment: commit_status
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - name: set check name
        id: set_check_name
        run: echo "${{ toJson(github) }}"
      - name: echo outputs
        run: echo "${{ toJson(needs.changes.outputs) }}"
      # - name: update status
      #   uses: gradio-app/github/actions/set-commit-status@main
      #   with:
      #     sha: ${{ needs.changes.outputs.sha }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     name: "storybook"
      #     run_id: ${{ needs.changes.outputs.run_id }}
